module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Introduction',
      collapsible: true,
      collapsed: false,
      items: ['introduction/get-started'],
    },
    {
      type: 'category',
      label: 'ARO Network',
      collapsible: true,
      collapsed: false,
      items: [
        'aro-network/architecture',
        'aro-network/network',
        'aro-network/work-proof',
        'aro-network/consensus',
        'aro-network/peer-edge',
      ],
    },
    {
      type: 'category',
      label: 'Node Operator Guide: Run ARO Nodes',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Become an ARO Node Operator',
          collapsible: true,
          collapsed: true,
          items: [
            'node-operator-guide/become-operator/idle-bandwidth',
            'node-operator-guide/become-operator/get-account',
            'node-operator-guide/become-operator/choose-node',
            'node-operator-guide/become-operator/aro-dashboard',
          ],
        },
        {
          type: 'category',
          label: 'ARO Pod',
          collapsible: true,
          collapsed: true,
          items: [
            'node-operator-guide/aro-pod/get-aro-pod',
            'node-operator-guide/aro-pod/aro-pod-installation-guide',
            'node-operator-guide/aro-pod/aro-pod-faq-troubleshooting',
          ],
        },
        'node-operator-guide/aro-link',
        {
          type: 'category',
          label: 'ARO Client',
          collapsible: true,
          collapsed: true,
          items: [
            'node-operator-guide/aro-client/choose-installation-method',
            'node-operator-guide/aro-client/aro-client-installation-guide-bare-metal',
            'node-operator-guide/aro-client/aro-client-installation-guide-vm',
            'node-operator-guide/aro-client/aro-client-installation-guide-installer-package',
            'node-operator-guide/aro-client/aro-client-faq-troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'ARO Lite',
          collapsible: true,
          collapsed: true,
          items: [
            'node-operator-guide/aro-lite/get-aro-lite',
            'node-operator-guide/aro-lite/aro-lite-installation-guide',
            'node-operator-guide/aro-lite/aro-lite-faq-troubleshooting',
          ],
        },
        {
          type: 'category',
          label: 'Improve Your Performance',
          collapsible: true,
          collapsed: true,
          items: [
            'node-operator-guide/improve-performance/network-nat-optimization',
            'node-operator-guide/improve-performance/router-nat-upnp-dmz-setup',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Developer Guide: Build on ARO',
      collapsible: true,
      collapsed: false,
      items: ['developer-guide/overview'],
    },
    {
      type: 'category',
      label: 'Edge Cloud Guide: Explore Edge Solutions',
      collapsible: true,
      collapsed: false,
      items: ['edge-cloud-guide/edge-cloud-solutions'],
    },
    {
      type: 'category',
      label: 'Campaign Hub',
      collapsible: true,
      collapsed: false,
      items: [
        'campaign-hub/aro-testnet',
        'campaign-hub/jade-rewards',
        'campaign-hub/referral-program',
      ],
    },
    {
      type: 'category',
      label: '$ARO Tokenomics',
      collapsible: true,
      collapsed: false,
      items: ['aro-tokenomics/tokenomics'],
    },
    {
      type: 'category',
      label: 'Appendix',
      collapsible: true,
      collapsed: false,
      items: [
        'appendix/useful-links',
        'appendix/terms-of-use',
        'appendix/privacy-policy',
      ],
    },
  ],
};